openapi: 3.0.0
info:
  title: 勤怠管理API
  version: 1.0.0
servers:
- url: https://mitei.com
  description: 本番API
paths:
  /api/employees:
    get:
      tags:
      - employee
      summary: 従業員リストを取得
      description: 従業員リストを取得
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employees'
components:
  schemas:
    Employees:
      type: array
      items:
        $ref: '#/components/schemas/Employee'
      x-schema-name: Employees
    Employee:
      required:
      - birthday
      - fullName
      - gender
      - position
      type: object
      properties:
        fullName:
          type: string
          description: |
            姓と名の間には半角スペースを設ける
          example: 山田 太郎
        gender:
          type: string
          description: 性別
          example: MALE
          enum:
          - MALE
          - FEMALE
          - NEITHER
          - NOT_ANSWER
        birthday:
          type: string
          description: "誕生日  \nISO 8601のYYYY-MM-DD形式\n"
          format: date
          example: 2000-10-10
        position:
          type: string
          description: 役割
          example: FULL_TIME
          enum:
          - FULL_TIME
          - PART_TIME
      example:
        birthday: 2000-10-10T00:00:00.000+0000
        gender: MALE
        fullName: 山田 太郎
        position: FULL_TIME
